#:schema node_modules/wrangler/config-schema.json
name = "doctor-notifier-periodic"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[triggers]
crons = ["*/10 * * * *"] # Run every 10 minutes

[[d1_databases]]
binding = "DB" 
database_name = "doctor-notifier"
database_id = "85d6beac-e8a5-45b0-a062-8cf297361e56"

[[services]]
binding = "SERVICE"
service = "doctor-notifier-worker"